language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '7'
- '6'
- '4'
before_script:
- npm prune
script:
- NODE_ENV=production npm run test:single
after_success:
- npm run report-coverage
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: npm
  email: l.franceschini@gmail.com
  api_key:
    secure: B1pQK5wI1B1/bssqCodajoKQJ7VXWhrMCyIYQnkMHwKK/s5msLqPu/Jx6/IiLqkeH7yMtWE0QELIEi2SzdXj6nsQVlOmJjwXgHWTs1s+BaQkA9dTm5Vm2w91uKSX65BvBncg7bIk25nclznIdaJQQBlbO+MLugunrkRGwNXJKeVUDoi/uaQYvMbGCiAOygeLECy3/FnC2gmLGLQXXnnXTfiUIRVMoy82icllarWlYLZl4F10GfKJ7nyhZ3S1HaxHjwuhgn5ilq1v+V81/+z8s9TRNIRxV/ztsfNZ5Pldsdz1RLgNhQ4U2T7Mj4UvCMmt3DBJOQcGaQJiMcARb2ub6b9tcB4X0EZFo6siYDpfybygIxE1Yh6AkQg+tPnk0BU/PWKdRUT5gXM88kHcngUUkGw3oPR/sNN1SsewnSF5xBMij9N9zxY63jew5KtjBwi4ngzp96rbEu08zQM5laVogE3SThRr195om9PCZjfRdTx8IDPtKXsaSv5kZeI2LaZsGBvuAUbmiRWibbsRoMqgkSxm9HniBvmuWJjVyUzhQZeXnYr8gH6/6qLOVNpXEX1kTHZmvtvm3+EdgV9+HSWkLDNyvX/7oXZn4B8n6QY6M4lnvQi3errN/x7ugMd+wDrkIq2Bx3yQMaVbSUOoHuPIKWygL3/ntdgxALbPAnEjec8=
  on:
    repo: Law78/node-app
    branch: master
